# Generated by Django 3.2.8 on 2021-11-17 19:55

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Nombre completo')),
                ('correo', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Correo electrónico')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Teléfono de contacto')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('usuario', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Usuario')),
                ('contrasena', models.CharField(max_length=256, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Contraseña')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es Administrador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
