# Generated by Django 3.2.8 on 2021-12-01 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(max_length=100, null=True, verbose_name='Departamento o Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.CharField(max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Teléfono de contacto'),
        ),
    ]
