# Generated by Django 3.2.8 on 2021-11-17 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Teléfono de contacto'),
        ),
    ]
