# Generated by Django 3.2.8 on 2021-11-18 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_App', '0002_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=256, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Contraseña'),
        ),
    ]
