# Generated by Django 3.2.8 on 2021-11-18 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_App', '0003_auto_20211118_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Contraseña'),
        ),
    ]
